@startuml
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

class Professor {
- name_: std::string
-books_: std::vector<std::weak_ptr<Book>>
}

class Book {
-title_: std::string

}

Professor -->  "0..*" Book: Wrote


@enduml