@startuml "Driving Scenario"

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

Package driving <<Frame>>{

class ElectricVehicle {
    -battery_capacity_: double
    -consumption_rate_: double
    +ElectricVehicle(model: std::string& <<const>>,\n\tcolor: std::string& <<const>>,\n\thorsepower: unsigned int,\n\tbattery_capacity: double)
    +charge_battery(): void
    +drive(distance: double): void <<virtual>> <<override>>
}

class GasolineVehicle {
    -tank_capacity_: double
    -fuel_consumption_rate_: double
    +GasolineVehicle(model: std::string& <<const>>,\n\tcolor: std::string& <<const>>,\n\thorsepower: unsigned int,\n\ttank_capacity: double)
    +refuel(): void
    +drive(distance: double): void <<virtual>> <<override>>
}

class Vehicle {
    -model_: std::string
    -color_: std::string
    -engine_: std::unique_ptr<driving::Engine>
    -driver_: std::shared_ptr<driving::Driver>
    +Vehicle(model: std::string& <<const>>,\n\tcolor: std::string& <<const>>,\n\thorsepower: unsigned int)
    +drive(distance: double): void <<virtual>> 
    +set_driver(driver: std::shared_ptr<driving::Driver>): void
}

' class Engine {

' }

' class Driver {

' }

' class Date {

' }



ElectricVehicle --up|> Vehicle: <<public>>
GasolineVehicle -up-|> Vehicle: <<public>>

' left of Vehicle
' GasolineVehicle


' Vehicle *-- "1" Engine : has <<unique>> >
' Vehicle o-- "1" Driver : is_driven_by <<shared>> >
' Driver *-- "1" Date : has_birthdate <<value>> >
}
@enduml
